In [12]:

import pandas as pd
import numpy as np

In [13]:
dict1={
    "Name":['Samar', 'Athar','Kaif','Shahwaiz'],
    "Marks":[99,98,97,95],
    "City":['Roorkee','Kannauj','Aligarh','Lucknow']
}

In [19]:
df=pd.DataFrame(dict1)

In [15]:
df

       Name  Marks     City
0     Samar     99  Roorkee
1     Athar     98  Kannauj
2      Kaif     97  Aligarh
3  Shahwaiz     95  Lucknow

In [21]:
newdf=pd.DataFrame(np.random.rand(100,8),index=np.arange(100))

In [22]:
newdf

,0,1,2,3,4,5,6,7
0,0.639233,0.987934,0.776471,0.009564,0.497942,0.230305,0.423188,0.227213
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512
2,0.917903,0.945934,0.015947,0.705705,0.683594,0.278658,0.301188,0.439558
3,0.217864,0.909983,0.992876,0.885682,0.713147,0.873974,0.507514,0.355722
4,0.055401,0.305002,0.755997,0.398721,0.992669,0.905399,0.981552,0.889350
...,...,...,...,...,...,...,...,...
95,0.254210,0.069810,0.934964,0.572499,0.666284,0.543726,0.504322,0.582387
96,0.216655,0.508891,0.093382,0.463118,0.590218,0.598328,0.975454,0.825458
97,0.148957,0.593920,0.069445,0.900862,0.355764,0.495742,0.759856,0.214163
98,0.769175,0.251970,0.533372,0.190045,0.290353,0.050878,0.047123,0.292107
99,0.909971,0.942461,0.474109,0.865619,0.483937,0.309075,0.905673,0.506463

In [23]:
newdf.describe()

,0,1,2,3,4,5,6,7
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,0.444402,0.506190,0.470866,0.460008,0.467666,0.522114,0.541470,0.516513
std,0.293020,0.298563,0.309248,0.261872,0.300571,0.266640,0.276092,0.287141
min,0.002220,0.000735,0.001237,0.009564,0.000854,0.023980,0.025608,0.024887
25%,0.171646,0.250828,0.193156,0.232290,0.186972,0.301471,0.308479,0.308359
50%,0.427326,0.512379,0.484224,0.459496,0.466348,0.545785,0.516111,0.480708
75%,0.664865,0.768275,0.690229,0.636983,0.750407,0.743850,0.788307,0.798846
max,0.984212,0.993706,0.999588,0.999069,0.992669,0.998761,0.996515,0.994155

In [25]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
5    float64
6    float64
7    float64
dtype: object

In [26]:
newdf[0][0]="Samar"

C:\Users\HP\AppData\Local\Temp\ipykernel_38836\2367720376.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0]="Samar"
C:\Users\HP\AppData\Local\Temp\ipykernel_38836\2367720376.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Samar' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0]="Samar"

In [27]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
5    float64
6    float64
7    float64
dtype: object

In [28]:
newdf.head(5)

,0,1,2,3,4,5,6,7
0,Samar,0.987934,0.776471,0.009564,0.497942,0.230305,0.423188,0.227213
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512
2,0.917903,0.945934,0.015947,0.705705,0.683594,0.278658,0.301188,0.439558
3,0.217864,0.909983,0.992876,0.885682,0.713147,0.873974,0.507514,0.355722
4,0.055401,0.305002,0.755997,0.398721,0.992669,0.905399,0.981552,0.889350

In [29]:
newdf.index

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype='int32')

In [31]:
newdf.columns

RangeIndex(start=0, stop=8, step=1)

In [32]:
newdf.to_numpy()

array([['Samar', 0.987933938881748, 0.7764709765933199,
        0.00956438528237713, 0.49794194131510905, 0.23030539964697128,
        0.42318753900546235, 0.22721336851242258],
       [0.38956284026515187, 0.5726259560002896, 0.2594428766982201,
        0.4412991845459242, 0.9334921575032713, 0.5662154725350815,
        0.7522692400424511, 0.5365122783404097],
       [0.9179028414722868, 0.9459343827062248, 0.015946854159163304,
        0.7057045443174784, 0.6835944090910618, 0.27865816625061357,
        0.3011875663898862, 0.4395578760634007],
       [0.2178644491045738, 0.9099834917557762, 0.992875713395376,
        0.8856818086963962, 0.7131471348951897, 0.873974312436953,
        0.5075142917810005, 0.35572190412669236],
       [0.05540091456691465, 0.30500205211455245, 0.7559966787546527,
        0.39872110987003273, 0.9926691554266724, 0.9053992272538671,
        0.9815524530731069, 0.8893496359336658],
       [0.5153363808970435, 0.2710887543649726, 0.19281950302000395,
        0.8009746016617473, 0.08474372623569482, 0.9987610657140535,
        0.23184736845205023, 0.8146745039766922],
       [0.5896193822677918, 0.551096891801196, 0.002855343311926384,
        0.6687808274355524, 0.09948188054786933, 0.1683043236132965,
        0.8656329758399803, 0.818911430597508],
       [0.49204340297526195, 0.6686802791487729, 0.23229783572014517,
        0.5029436931482308, 0.412957948671847, 0.9038197513412727,
        0.21550734529513715, 0.5338523656338662],
       [0.7660500546021245, 0.5093665934857143, 0.39067427746180683,
        0.45587355564258325, 0.29759608852954333, 0.3774806774137808,
        0.4312374718874681, 0.024887446917211342],
       [0.004823733661536211, 0.19397578648222435, 0.36197779059730006,
        0.4250813955355608, 0.08229963562023113, 0.2524453303925215,
        0.5935760460022143, 0.03953707699054032],
       [0.0022197589911049365, 0.3769300527192263, 0.729925540976286,
        0.7553994962537048, 0.919931931440791, 0.7770575699742358,
        0.28546944524079176, 0.15212520978074184],
       [0.5730669773792779, 0.5600646035599427, 0.5246849904888595,
        0.13196963236000692, 0.5544737437793428, 0.6815771746544689,
        0.6491579103123666, 0.2200504131053388],
       [0.6561459835896045, 0.905338445823998, 0.9162192441352673,
        0.5218075734168295, 0.12641659183269094, 0.20691248088233105,
        0.8390315989886583, 0.7978942806485236],
       [0.2744656618891138, 0.9649369224325418, 0.6254995813217139,
        0.5374625027833613, 0.7502208433150303, 0.46719742696053035,
        0.4609975658630666, 0.4758472129581677],
       [0.42818706104102866, 0.8564824377384694, 0.992960511518005,
        0.3984965417585048, 0.8216867998292469, 0.5070668895699617,
        0.9561126902249888, 0.8475313827047187],
       [0.5190029701079293, 0.48595765340814145, 0.893283632526895,
        0.2861771932248629, 0.5592863241357646, 0.02476729762648422,
        0.5412052560351955, 0.32915618761897814],
       [0.611485888465551, 0.6202444225826003, 0.3799604380530246,
        0.7665304403733977, 0.1619267524077257, 0.8566252057543763,
        0.4449206301064038, 0.3215288406092802],
       [0.5399258541353246, 0.9594769316261044, 0.8937021808852185,
        0.21896185645198007, 0.3693417386386547, 0.5726091338758352,
        0.5319660879341628, 0.790657722204299],
       [0.13154709333491565, 0.2003426919894723, 0.6931820865145522,
        0.4489901793698947, 0.47485781660192317, 0.4838849821461205,
        0.29574559706656467, 0.8945850668803143],
       [0.16440194445135847, 0.7883522582405482, 0.26228064421125086,
        0.8654255316449492, 0.2803468888196998, 0.5223695231436687,
        0.310422243907546, 0.7548156750443402],
       [0.5595358792721111, 0.2450708347052346, 0.6598629793204545,
        0.6176664572320202, 0.38358484234003787, 0.6875911809718572,
        0.6313235672236196, 0.6459481810711946],
       [0.6717003254305152, 0.5506070297302338, 0.1613460087328319,
        0.5304210074470828, 0.8812855664208774, 0.5608917455778996,
        0.48160007937016114, 0.5129921986344356],
       [0.6421387521988918, 0.5735261901074239, 0.17293823142386155,
        0.8072245362758546, 0.31445936746089376, 0.8348377311843953,
        0.6415354553721607, 0.17451344621564668],
       [0.09095658691496711, 0.4964087899548175, 0.3954913478160941,
        0.4009471852037152, 0.9139588067465426, 0.3623480438900589,
        0.8990390591610816, 0.48414135643306966],
       [0.7853087234237272, 0.9293779491363301, 0.5666324823196383,
        0.12419321980976328, 0.4229208156083647, 0.36012902593716545,
        0.845863588107109, 0.9482511491838349],
       [0.1740611709716141, 0.1327250839723274, 0.6475905559115225,
        0.904671865154727, 0.19532024560489303, 0.6179249909623825,
        0.3343918327747861, 0.94128205414345],
       [0.04914920113154986, 0.942303612858904, 0.39425163195265456,
        0.3045065870380663, 0.5067744125789624, 0.21010979545428055,
        0.2605930530369799, 0.6965615891362488],
       [0.963350778989552, 0.51539091199702, 0.8077400465966349,
        0.34127071030291933, 0.06696482365825618, 0.12932274169460334,
        0.20796987381717214, 0.9918929115642473],
       [0.837466966618419, 0.508879113410009, 0.19326802237036134,
        0.5688563905778722, 0.5752229315925438, 0.5971752199899153,
        0.8634542154497384, 0.9531359763101356],
       [0.8080007278834351, 0.1331479904947197, 0.03048877061155808,
        0.15977777018128658, 0.08201564254971683, 0.9008756901377162,
        0.37217594190010905, 0.9636796237146567],
       [0.8770181382584313, 0.5979215175759997, 0.404799049391648,
        0.1210178866678504, 0.9091900536598724, 0.4319782234133025,
        0.5244676325965832, 0.5647253524588791],
       [0.7051786114819268, 0.35022554533564954, 0.9664115666087587,
        0.7431200157452418, 0.9428653767023968, 0.7421215430721934,
        0.6681374309405406, 0.21655299276917728],
       [0.1342690960394134, 0.4158889748178678, 0.3039837727548079,
        0.18317515522447136, 0.5319433375565933, 0.713118293557529,
        0.8918275357648838, 0.07248669730477442],
       [0.16294605529932848, 0.9619477493823261, 0.6892441753887715,
        0.8141215512916867, 0.8996892491312983, 0.7608664229519356,
        0.13879120311554016, 0.04898238984860248],
       [0.5203363726611523, 0.7857753656894098, 0.6626924456178774,
        0.5104583048119601, 0.08448762955860556, 0.7001986595999381,
        0.2153449223667644, 0.06764472170400238],
       [0.8445270354405962, 0.8482955352916408, 0.3650506578876951,
        0.6350808102083878, 0.7799806256158806, 0.4093158319407547,
        0.9906309047873553, 0.4905835185158597],
       [0.9514003038541308, 0.46329812644178225, 0.49877412330308013,
        0.4957031661013952, 0.2237309839596726, 0.5478440700917637,
        0.3359640601560714, 0.35754682868470733],
       [0.29254214367959475, 0.9937055586298973, 0.022449512503887603,
        0.34219235314461616, 0.14881753720075863, 0.810245740902589,
        0.8280849731342661, 0.9089398723230449],
       [0.18827290257459994, 0.4360608774181286, 0.10194293496730455,
        0.7501838682923874, 0.31623155906636957, 0.6380307190807601,
        0.025608084044890234, 0.4269551768055976],
       [0.09843228829834239, 0.05366824671339354, 0.7989278768057589,
        0.5566975567531887, 0.8433506860747816, 0.6019723038053719,
        0.47537911584658843, 0.9862741241248631],
       [0.06673517968439724, 0.9738264262542542, 0.12221227440126659,
        0.5233530227270449, 0.8050336068003986, 0.20497853993425574,
        0.7463629691364436, 0.41254447913796843],
       [0.4913709939941, 0.049618900293636914, 0.38818437592395316,
        0.2924197281869396, 0.06176589925600828, 0.5365463815151751,
        0.929745920917356, 0.47613217866214497],
       [0.4581013631703459, 0.16888325963658868, 0.05859278671326762,
        0.5769765018562205, 0.8986845269767919, 0.14463724732470695,
        0.03698190901575993, 0.8615463014084503],
       [0.6052334443103015, 0.7891791983739458, 0.5134130370003317,
        0.12728055490122936, 0.16085068492148535, 0.5351061809508342,
        0.5128374917510506, 0.6063715488539712],
       [0.11134390719109266, 0.5579909546680787, 0.9928903417689838,
        0.7456966838040222, 0.6073088852277915, 0.1729679423528051,
        0.6176479456406265, 0.9941554462752722],
       [0.9842118234165258, 0.29641808059270514, 0.6091006034216591,
        0.5801479466840205, 0.45783887754138186, 0.7529053377522371,
        0.4467252929704474, 0.3631045473679144],
       [0.9117382622558954, 0.5654675847700502, 0.6492731661507853,
        0.8231750734858947, 0.9225244869460583, 0.4793573591385004,
        0.1752611711313713, 0.12063717766919668],
       [0.370147424529614, 0.6490586132015439, 0.48722531266694413,
        0.12998472985985288, 0.23633917588870457, 0.9715858961467809,
        0.7259226225611433, 0.4759548398862735],
       [0.5156284631156722, 0.18099338949644905, 0.5995411168413274,
        0.31164296958508164, 0.3233502324666313, 0.4082605145808199,
        0.7958020336802204, 0.9290256218774747],
       [0.14636986843995126, 0.3293796807302003, 0.9810248916707871,
        0.24510052518069436, 0.007164936931372545, 0.3159219006828995,
        0.7187146627701394, 0.0801172806390702],
       [0.6626068733793014, 0.8324260867785817, 0.574759747535892,
        0.6029809689286456, 0.29560456630980436, 0.11125760015903707,
        0.20182911589760544, 0.9819810945083787],
       [0.8674975480460619, 0.3274393382409192, 0.25839688514663783,
        0.013743934291816196, 0.01802357189930659, 0.12825224934047497,
        0.8881005967730659, 0.45486718246297864],
       [0.3283475095846181, 0.2912255605087498, 0.09941688966555906,
        0.11226227913956044, 0.9312600536252692, 0.3867515851315608,
        0.392084217264706, 0.3419315067443578],
       [0.8471883238307605, 0.780236214087953, 0.0012366172598322622,
        0.4679144736637977, 0.822169885259447, 0.7438011439932207,
        0.7858090914391694, 0.6131058353778688],
       [0.6320771253631183, 0.6845372285983986, 0.11578908902368323,
        0.0718856704964922, 0.8252321062725123, 0.3962326506140492,
        0.6979168087093319, 0.1915200301701797],
       [0.3398585743982626, 0.695037036280628, 0.8517699835022066,
        0.22163584592033825, 0.2888405673993266, 0.9741514124187408,
        0.5818982438592949, 0.4809533907171779],
       [0.04298994143230239, 0.3895542891320145, 0.004822694794050175,
        0.43532134505379183, 0.6615481198150905, 0.8293623474105373,
        0.9965152524527011, 0.13303555501243625],
       [0.21367109316136979, 0.8313686178805931, 0.6561221269029864,
        0.12160479390003287, 0.0008544611497118826, 0.2755996431470944,
        0.13323556639603984, 0.7119867441147737],
       [0.22471574468622124, 0.16699229487867706, 0.12217477793387121,
        0.6426905277117085, 0.5097642471942604, 0.06488575527399187,
        0.6259332170466132, 0.2891046473772141],
       [0.2000880112410458, 0.8579269342620308, 0.21331202180584263,
        0.9990689588405549, 0.8196289862991003, 0.16581637421934503,
        0.6874703264614612, 0.040174375875757895],
       [0.6883848105425294, 0.12565462214223144, 0.5648013392130578,
        0.12464281002840294, 0.40834820747887257, 0.5102402679628455,
        0.24729200286906872, 0.6672651294941204],
       [0.7508958653235499, 0.16388583395936862, 0.24532148321407032,
        0.490022619439751, 0.7509643447804307, 0.7208892865122399,
        0.47891187058832296, 0.4823256287031715],
       [0.43812519602257527, 0.16814595838522084, 0.25388023428471906,
        0.7637480273128937, 0.48423757896747865, 0.5239335462000622,
        0.11231785028102026, 0.3136574268377511],
       [0.6296367500372962, 0.05590688289958401, 0.6087736632916724,
        0.362581007083576, 0.1301874956593677, 0.743997718395096,
        0.2759882793849152, 0.4009505262684131],
       [0.15203924364075072, 0.6448721197786962, 0.48122351252873985,
        0.28454130407300815, 0.5543462400157576, 0.643273409499844,
        0.2697156284232747, 0.4749555286639596],
       [0.6716374793761372, 0.24740150174968223, 0.5233986722846208,
        0.6054205364019678, 0.2170276555723858, 0.048229072427766084,
        0.39901290754525676, 0.9028877683659621],
       [0.42646398891932835, 0.26414589224524376, 0.29100426285660297,
        0.08144321265302334, 0.2831800814244343, 0.3765982075715456,
        0.7617840389571752, 0.18222916432738823],
       [0.6566972760058449, 0.04582364833437402, 0.14213775366555748,
        0.03424105090156082, 0.06301799934653685, 0.023979617568325562,
        0.8891481859989168, 0.6618167394579],
       [0.3571127026742119, 0.9005190926078962, 0.024894745315627076,
        0.9233862293079524, 0.3775039423037755, 0.8327064138054184,
        0.37724289137728306, 0.11458288734305266],
       [0.09880363885394283, 0.7387335982209043, 0.5022030993241352,
        0.4058595413581195, 0.14486497625932182, 0.8318722341976073,
        0.5173393390322915, 0.20059821669312872],
       [0.33243557276641256, 0.5701027916813978, 0.813532658678997,
        0.19471723121225581, 0.5361073324455908, 0.6233625864282174,
        0.811051392419748, 0.8119836151798084],
       [0.2600956837407159, 0.9821757812518139, 0.8871723246381698,
        0.5910714882697923, 0.22283892568828279, 0.3822576124360124,
        0.7509865805347486, 0.3847578462711436],
       [0.7540768419353362, 0.7293341764002473, 0.6972687630464347,
        0.31863429300466417, 0.0955510676527348, 0.7386515838331474,
        0.113453779770328, 0.8782005803497814],
       [0.10975969350659476, 0.689655267421493, 0.5167258790028013,
        0.3065074521558818, 0.6900996578356159, 0.8785094276847978,
        0.43003253476112224, 0.3116935910079903],
       [0.2216653811812308, 0.8695821423474349, 0.020359071789563088,
        0.29736878911413644, 0.7655028448332449, 0.8064039480981279,
        0.9388360327090571, 0.24401879145055683],
       [0.37308681205980865, 0.6054711354774165, 0.15884766192826494,
        0.508741509224141, 0.10388871390096821, 0.06931458493807052,
        0.9526039246888919, 0.06454243163554796],
       [0.09165615644616953, 0.3183444421644962, 0.14126812858026694,
        0.23280766222421756, 0.7803161093243252, 0.7198535425677197,
        0.1092717330035069, 0.40607818658113526],
       [0.5910743187326963, 0.43725518919510986, 0.4068075308961264,
        0.1315862946431271, 0.4151590897802603, 0.6593560499149241,
        0.835884459570114, 0.3612744672268766],
       [0.05131932707014941, 0.7203272759723658, 0.9788627899981445,
        0.3858831547877355, 0.11567466032503826, 0.7285838599852268,
        0.7073983307798202, 0.9202084405726575],
       [0.2593690151657285, 0.029036767112275097, 0.30513046846432623,
        0.6306511107841748, 0.6100114991207368, 0.573399853026508,
        0.7568571078957629, 0.9915605323117828],
       [0.7937956131503738, 0.17687811368194128, 0.2686949986638416,
        0.6583054327481571, 0.8226609106518405, 0.6407376049012115,
        0.04299567564062634, 0.4804620259246417],
       [0.9182034143678475, 0.764287526438516, 0.9995875939199494,
        0.1625368626646715, 0.03616848889578517, 0.4448181031455374,
        0.8336354839089011, 0.4131316214403147],
       [0.32593688625019057, 0.2678834501044227, 0.818134073060548,
        0.7644188139267462, 0.21674633585783198, 0.25156912133912546,
        0.3806628961765044, 0.858669271143612],
       [0.14557374486842622, 0.000734568830486948, 0.10922257506708621,
        0.11457595994978664, 0.6961144723037657, 0.7617808356016411,
        0.07669882011514728, 0.801702049587647],
       [0.6032077699072256, 0.08436866163098722, 0.12984882015246613,
        0.9786632979305651, 0.9349453063505614, 0.10256336723184656,
        0.674232495649627, 0.29835434927420834],
       [0.050584299599867544, 0.041570003880418205, 0.6354187481674417,
        0.3986785063857874, 0.5084595944730074, 0.8670474706851001,
        0.36140857590939235, 0.2409213929056816],
       [0.009388211498804422, 0.023620258933618743, 0.9736408164262266,
        0.7399078862777397, 0.7488062528640038, 0.2554277257644364,
        0.30264925049127145, 0.9461388999428614],
       [0.07883988731918024, 0.0017270065429840775, 0.6039845030941133,
        0.3639532626616888, 0.5262313183626182, 0.8652658919103794,
        0.40678108805346525, 0.5755788386022481],
       [0.9540309618644877, 0.5327240403611321, 0.6855901805793,
        0.5640275893197222, 0.13744218351987447, 0.14872455349028435,
        0.5148825626731063, 0.6493621882183533],
       [0.6405119756470511, 0.20246051560863665, 0.37182559625980605,
        0.482139301808187, 0.41567697388824854, 0.2100975454404984,
        0.8397969625400235, 0.34510443543833025],
       [0.9489127164550427, 0.6521237457137699, 0.014751187621828254,
        0.02378528081752518, 0.9743674434170639, 0.7452663445973192,
        0.8286861562596548, 0.6489608824012336],
       [0.21414161657249864, 0.48915308382915756, 0.2006957966886107,
        0.23073574278269415, 0.0980793469559107, 0.32074356202586984,
        0.9063595736583626, 0.3935710413318959],
       [0.2534949697648776, 0.3944440560628507, 0.9776990796380705,
        0.9719417901440758, 0.8284878857707938, 0.6803207176868075,
        0.494606674336053, 0.5837932998206363],
       [0.27142073018702517, 0.48636409182146867, 0.6432176370937984,
        0.147565813233259, 0.0918713785953098, 0.8284223449214373,
        0.26330185108612425, 0.5989176732889872],
       [0.15402149868463488, 0.8416710917084362, 0.9492409382006283,
        0.5515293362864999, 0.1021451693521147, 0.7847008657654228,
        0.34524618789660944, 0.34469353408699466],
       [0.25421020971775665, 0.06981048581042482, 0.9349640631240353,
        0.5724989846173517, 0.666283973555698, 0.5437259799913033,
        0.5043224222341601, 0.5823874271596938],
       [0.21665528682150637, 0.5088912617415079, 0.09338202001557094,
        0.4631176619674955, 0.590218200999245, 0.5983282623441194,
        0.975454432507087, 0.8254580108018265],
       [0.14895656357021236, 0.5939203722764016, 0.06944539721023679,
        0.9008623498806172, 0.35576381563735016, 0.4957423619715833,
        0.7598556017713788, 0.21416337375075578],
       [0.7691753685450565, 0.25197024245583044, 0.5333722764366433,
        0.19004542209953035, 0.2903526177361172, 0.05087834519781875,
        0.04712317109672659, 0.29210675167594224],
       [0.9099705747489388, 0.9424611619851552, 0.4741088115856742,
        0.8656187734037556, 0.48393692918726006, 0.30907496524914324,
        0.9056731833417734, 0.5064627806770224]], dtype=object)

In [33]:
newdf[0][0]

'Samar'

In [34]:
newdf[0][0]=0.5

In [35]:
newdf.to_numpy()

array([[0.5, 0.987933938881748, 0.7764709765933199, 0.00956438528237713,
        0.49794194131510905, 0.23030539964697128, 0.42318753900546235,
        0.22721336851242258],
       [0.38956284026515187, 0.5726259560002896, 0.2594428766982201,
        0.4412991845459242, 0.9334921575032713, 0.5662154725350815,
        0.7522692400424511, 0.5365122783404097],
       [0.9179028414722868, 0.9459343827062248, 0.015946854159163304,
        0.7057045443174784, 0.6835944090910618, 0.27865816625061357,
        0.3011875663898862, 0.4395578760634007],
       [0.2178644491045738, 0.9099834917557762, 0.992875713395376,
        0.8856818086963962, 0.7131471348951897, 0.873974312436953,
        0.5075142917810005, 0.35572190412669236],
       [0.05540091456691465, 0.30500205211455245, 0.7559966787546527,
        0.39872110987003273, 0.9926691554266724, 0.9053992272538671,
        0.9815524530731069, 0.8893496359336658],
       [0.5153363808970435, 0.2710887543649726, 0.19281950302000395,
        0.8009746016617473, 0.08474372623569482, 0.9987610657140535,
        0.23184736845205023, 0.8146745039766922],
       [0.5896193822677918, 0.551096891801196, 0.002855343311926384,
        0.6687808274355524, 0.09948188054786933, 0.1683043236132965,
        0.8656329758399803, 0.818911430597508],
       [0.49204340297526195, 0.6686802791487729, 0.23229783572014517,
        0.5029436931482308, 0.412957948671847, 0.9038197513412727,
        0.21550734529513715, 0.5338523656338662],
       [0.7660500546021245, 0.5093665934857143, 0.39067427746180683,
        0.45587355564258325, 0.29759608852954333, 0.3774806774137808,
        0.4312374718874681, 0.024887446917211342],
       [0.004823733661536211, 0.19397578648222435, 0.36197779059730006,
        0.4250813955355608, 0.08229963562023113, 0.2524453303925215,
        0.5935760460022143, 0.03953707699054032],
       [0.0022197589911049365, 0.3769300527192263, 0.729925540976286,
        0.7553994962537048, 0.919931931440791, 0.7770575699742358,
        0.28546944524079176, 0.15212520978074184],
       [0.5730669773792779, 0.5600646035599427, 0.5246849904888595,
        0.13196963236000692, 0.5544737437793428, 0.6815771746544689,
        0.6491579103123666, 0.2200504131053388],
       [0.6561459835896045, 0.905338445823998, 0.9162192441352673,
        0.5218075734168295, 0.12641659183269094, 0.20691248088233105,
        0.8390315989886583, 0.7978942806485236],
       [0.2744656618891138, 0.9649369224325418, 0.6254995813217139,
        0.5374625027833613, 0.7502208433150303, 0.46719742696053035,
        0.4609975658630666, 0.4758472129581677],
       [0.42818706104102866, 0.8564824377384694, 0.992960511518005,
        0.3984965417585048, 0.8216867998292469, 0.5070668895699617,
        0.9561126902249888, 0.8475313827047187],
       [0.5190029701079293, 0.48595765340814145, 0.893283632526895,
        0.2861771932248629, 0.5592863241357646, 0.02476729762648422,
        0.5412052560351955, 0.32915618761897814],
       [0.611485888465551, 0.6202444225826003, 0.3799604380530246,
        0.7665304403733977, 0.1619267524077257, 0.8566252057543763,
        0.4449206301064038, 0.3215288406092802],
       [0.5399258541353246, 0.9594769316261044, 0.8937021808852185,
        0.21896185645198007, 0.3693417386386547, 0.5726091338758352,
        0.5319660879341628, 0.790657722204299],
       [0.13154709333491565, 0.2003426919894723, 0.6931820865145522,
        0.4489901793698947, 0.47485781660192317, 0.4838849821461205,
        0.29574559706656467, 0.8945850668803143],
       [0.16440194445135847, 0.7883522582405482, 0.26228064421125086,
        0.8654255316449492, 0.2803468888196998, 0.5223695231436687,
        0.310422243907546, 0.7548156750443402],
       [0.5595358792721111, 0.2450708347052346, 0.6598629793204545,
        0.6176664572320202, 0.38358484234003787, 0.6875911809718572,
        0.6313235672236196, 0.6459481810711946],
       [0.6717003254305152, 0.5506070297302338, 0.1613460087328319,
        0.5304210074470828, 0.8812855664208774, 0.5608917455778996,
        0.48160007937016114, 0.5129921986344356],
       [0.6421387521988918, 0.5735261901074239, 0.17293823142386155,
        0.8072245362758546, 0.31445936746089376, 0.8348377311843953,
        0.6415354553721607, 0.17451344621564668],
       [0.09095658691496711, 0.4964087899548175, 0.3954913478160941,
        0.4009471852037152, 0.9139588067465426, 0.3623480438900589,
        0.8990390591610816, 0.48414135643306966],
       [0.7853087234237272, 0.9293779491363301, 0.5666324823196383,
        0.12419321980976328, 0.4229208156083647, 0.36012902593716545,
        0.845863588107109, 0.9482511491838349],
       [0.1740611709716141, 0.1327250839723274, 0.6475905559115225,
        0.904671865154727, 0.19532024560489303, 0.6179249909623825,
        0.3343918327747861, 0.94128205414345],
       [0.04914920113154986, 0.942303612858904, 0.39425163195265456,
        0.3045065870380663, 0.5067744125789624, 0.21010979545428055,
        0.2605930530369799, 0.6965615891362488],
       [0.963350778989552, 0.51539091199702, 0.8077400465966349,
        0.34127071030291933, 0.06696482365825618, 0.12932274169460334,
        0.20796987381717214, 0.9918929115642473],
       [0.837466966618419, 0.508879113410009, 0.19326802237036134,
        0.5688563905778722, 0.5752229315925438, 0.5971752199899153,
        0.8634542154497384, 0.9531359763101356],
       [0.8080007278834351, 0.1331479904947197, 0.03048877061155808,
        0.15977777018128658, 0.08201564254971683, 0.9008756901377162,
        0.37217594190010905, 0.9636796237146567],
       [0.8770181382584313, 0.5979215175759997, 0.404799049391648,
        0.1210178866678504, 0.9091900536598724, 0.4319782234133025,
        0.5244676325965832, 0.5647253524588791],
       [0.7051786114819268, 0.35022554533564954, 0.9664115666087587,
        0.7431200157452418, 0.9428653767023968, 0.7421215430721934,
        0.6681374309405406, 0.21655299276917728],
       [0.1342690960394134, 0.4158889748178678, 0.3039837727548079,
        0.18317515522447136, 0.5319433375565933, 0.713118293557529,
        0.8918275357648838, 0.07248669730477442],
       [0.16294605529932848, 0.9619477493823261, 0.6892441753887715,
        0.8141215512916867, 0.8996892491312983, 0.7608664229519356,
        0.13879120311554016, 0.04898238984860248],
       [0.5203363726611523, 0.7857753656894098, 0.6626924456178774,
        0.5104583048119601, 0.08448762955860556, 0.7001986595999381,
        0.2153449223667644, 0.06764472170400238],
       [0.8445270354405962, 0.8482955352916408, 0.3650506578876951,
        0.6350808102083878, 0.7799806256158806, 0.4093158319407547,
        0.9906309047873553, 0.4905835185158597],
       [0.9514003038541308, 0.46329812644178225, 0.49877412330308013,
        0.4957031661013952, 0.2237309839596726, 0.5478440700917637,
        0.3359640601560714, 0.35754682868470733],
       [0.29254214367959475, 0.9937055586298973, 0.022449512503887603,
        0.34219235314461616, 0.14881753720075863, 0.810245740902589,
        0.8280849731342661, 0.9089398723230449],
       [0.18827290257459994, 0.4360608774181286, 0.10194293496730455,
        0.7501838682923874, 0.31623155906636957, 0.6380307190807601,
        0.025608084044890234, 0.4269551768055976],
       [0.09843228829834239, 0.05366824671339354, 0.7989278768057589,
        0.5566975567531887, 0.8433506860747816, 0.6019723038053719,
        0.47537911584658843, 0.9862741241248631],
       [0.06673517968439724, 0.9738264262542542, 0.12221227440126659,
        0.5233530227270449, 0.8050336068003986, 0.20497853993425574,
        0.7463629691364436, 0.41254447913796843],
       [0.4913709939941, 0.049618900293636914, 0.38818437592395316,
        0.2924197281869396, 0.06176589925600828, 0.5365463815151751,
        0.929745920917356, 0.47613217866214497],
       [0.4581013631703459, 0.16888325963658868, 0.05859278671326762,
        0.5769765018562205, 0.8986845269767919, 0.14463724732470695,
        0.03698190901575993, 0.8615463014084503],
       [0.6052334443103015, 0.7891791983739458, 0.5134130370003317,
        0.12728055490122936, 0.16085068492148535, 0.5351061809508342,
        0.5128374917510506, 0.6063715488539712],
       [0.11134390719109266, 0.5579909546680787, 0.9928903417689838,
        0.7456966838040222, 0.6073088852277915, 0.1729679423528051,
        0.6176479456406265, 0.9941554462752722],
       [0.9842118234165258, 0.29641808059270514, 0.6091006034216591,
        0.5801479466840205, 0.45783887754138186, 0.7529053377522371,
        0.4467252929704474, 0.3631045473679144],
       [0.9117382622558954, 0.5654675847700502, 0.6492731661507853,
        0.8231750734858947, 0.9225244869460583, 0.4793573591385004,
        0.1752611711313713, 0.12063717766919668],
       [0.370147424529614, 0.6490586132015439, 0.48722531266694413,
        0.12998472985985288, 0.23633917588870457, 0.9715858961467809,
        0.7259226225611433, 0.4759548398862735],
       [0.5156284631156722, 0.18099338949644905, 0.5995411168413274,
        0.31164296958508164, 0.3233502324666313, 0.4082605145808199,
        0.7958020336802204, 0.9290256218774747],
       [0.14636986843995126, 0.3293796807302003, 0.9810248916707871,
        0.24510052518069436, 0.007164936931372545, 0.3159219006828995,
        0.7187146627701394, 0.0801172806390702],
       [0.6626068733793014, 0.8324260867785817, 0.574759747535892,
        0.6029809689286456, 0.29560456630980436, 0.11125760015903707,
        0.20182911589760544, 0.9819810945083787],
       [0.8674975480460619, 0.3274393382409192, 0.25839688514663783,
        0.013743934291816196, 0.01802357189930659, 0.12825224934047497,
        0.8881005967730659, 0.45486718246297864],
       [0.3283475095846181, 0.2912255605087498, 0.09941688966555906,
        0.11226227913956044, 0.9312600536252692, 0.3867515851315608,
        0.392084217264706, 0.3419315067443578],
       [0.8471883238307605, 0.780236214087953, 0.0012366172598322622,
        0.4679144736637977, 0.822169885259447, 0.7438011439932207,
        0.7858090914391694, 0.6131058353778688],
       [0.6320771253631183, 0.6845372285983986, 0.11578908902368323,
        0.0718856704964922, 0.8252321062725123, 0.3962326506140492,
        0.6979168087093319, 0.1915200301701797],
       [0.3398585743982626, 0.695037036280628, 0.8517699835022066,
        0.22163584592033825, 0.2888405673993266, 0.9741514124187408,
        0.5818982438592949, 0.4809533907171779],
       [0.04298994143230239, 0.3895542891320145, 0.004822694794050175,
        0.43532134505379183, 0.6615481198150905, 0.8293623474105373,
        0.9965152524527011, 0.13303555501243625],
       [0.21367109316136979, 0.8313686178805931, 0.6561221269029864,
        0.12160479390003287, 0.0008544611497118826, 0.2755996431470944,
        0.13323556639603984, 0.7119867441147737],
       [0.22471574468622124, 0.16699229487867706, 0.12217477793387121,
        0.6426905277117085, 0.5097642471942604, 0.06488575527399187,
        0.6259332170466132, 0.2891046473772141],
       [0.2000880112410458, 0.8579269342620308, 0.21331202180584263,
        0.9990689588405549, 0.8196289862991003, 0.16581637421934503,
        0.6874703264614612, 0.040174375875757895],
       [0.6883848105425294, 0.12565462214223144, 0.5648013392130578,
        0.12464281002840294, 0.40834820747887257, 0.5102402679628455,
        0.24729200286906872, 0.6672651294941204],
       [0.7508958653235499, 0.16388583395936862, 0.24532148321407032,
        0.490022619439751, 0.7509643447804307, 0.7208892865122399,
        0.47891187058832296, 0.4823256287031715],
       [0.43812519602257527, 0.16814595838522084, 0.25388023428471906,
        0.7637480273128937, 0.48423757896747865, 0.5239335462000622,
        0.11231785028102026, 0.3136574268377511],
       [0.6296367500372962, 0.05590688289958401, 0.6087736632916724,
        0.362581007083576, 0.1301874956593677, 0.743997718395096,
        0.2759882793849152, 0.4009505262684131],
       [0.15203924364075072, 0.6448721197786962, 0.48122351252873985,
        0.28454130407300815, 0.5543462400157576, 0.643273409499844,
        0.2697156284232747, 0.4749555286639596],
       [0.6716374793761372, 0.24740150174968223, 0.5233986722846208,
        0.6054205364019678, 0.2170276555723858, 0.048229072427766084,
        0.39901290754525676, 0.9028877683659621],
       [0.42646398891932835, 0.26414589224524376, 0.29100426285660297,
        0.08144321265302334, 0.2831800814244343, 0.3765982075715456,
        0.7617840389571752, 0.18222916432738823],
       [0.6566972760058449, 0.04582364833437402, 0.14213775366555748,
        0.03424105090156082, 0.06301799934653685, 0.023979617568325562,
        0.8891481859989168, 0.6618167394579],
       [0.3571127026742119, 0.9005190926078962, 0.024894745315627076,
        0.9233862293079524, 0.3775039423037755, 0.8327064138054184,
        0.37724289137728306, 0.11458288734305266],
       [0.09880363885394283, 0.7387335982209043, 0.5022030993241352,
        0.4058595413581195, 0.14486497625932182, 0.8318722341976073,
        0.5173393390322915, 0.20059821669312872],
       [0.33243557276641256, 0.5701027916813978, 0.813532658678997,
        0.19471723121225581, 0.5361073324455908, 0.6233625864282174,
        0.811051392419748, 0.8119836151798084],
       [0.2600956837407159, 0.9821757812518139, 0.8871723246381698,
        0.5910714882697923, 0.22283892568828279, 0.3822576124360124,
        0.7509865805347486, 0.3847578462711436],
       [0.7540768419353362, 0.7293341764002473, 0.6972687630464347,
        0.31863429300466417, 0.0955510676527348, 0.7386515838331474,
        0.113453779770328, 0.8782005803497814],
       [0.10975969350659476, 0.689655267421493, 0.5167258790028013,
        0.3065074521558818, 0.6900996578356159, 0.8785094276847978,
        0.43003253476112224, 0.3116935910079903],
       [0.2216653811812308, 0.8695821423474349, 0.020359071789563088,
        0.29736878911413644, 0.7655028448332449, 0.8064039480981279,
        0.9388360327090571, 0.24401879145055683],
       [0.37308681205980865, 0.6054711354774165, 0.15884766192826494,
        0.508741509224141, 0.10388871390096821, 0.06931458493807052,
        0.9526039246888919, 0.06454243163554796],
       [0.09165615644616953, 0.3183444421644962, 0.14126812858026694,
        0.23280766222421756, 0.7803161093243252, 0.7198535425677197,
        0.1092717330035069, 0.40607818658113526],
       [0.5910743187326963, 0.43725518919510986, 0.4068075308961264,
        0.1315862946431271, 0.4151590897802603, 0.6593560499149241,
        0.835884459570114, 0.3612744672268766],
       [0.05131932707014941, 0.7203272759723658, 0.9788627899981445,
        0.3858831547877355, 0.11567466032503826, 0.7285838599852268,
        0.7073983307798202, 0.9202084405726575],
       [0.2593690151657285, 0.029036767112275097, 0.30513046846432623,
        0.6306511107841748, 0.6100114991207368, 0.573399853026508,
        0.7568571078957629, 0.9915605323117828],
       [0.7937956131503738, 0.17687811368194128, 0.2686949986638416,
        0.6583054327481571, 0.8226609106518405, 0.6407376049012115,
        0.04299567564062634, 0.4804620259246417],
       [0.9182034143678475, 0.764287526438516, 0.9995875939199494,
        0.1625368626646715, 0.03616848889578517, 0.4448181031455374,
        0.8336354839089011, 0.4131316214403147],
       [0.32593688625019057, 0.2678834501044227, 0.818134073060548,
        0.7644188139267462, 0.21674633585783198, 0.25156912133912546,
        0.3806628961765044, 0.858669271143612],
       [0.14557374486842622, 0.000734568830486948, 0.10922257506708621,
        0.11457595994978664, 0.6961144723037657, 0.7617808356016411,
        0.07669882011514728, 0.801702049587647],
       [0.6032077699072256, 0.08436866163098722, 0.12984882015246613,
        0.9786632979305651, 0.9349453063505614, 0.10256336723184656,
        0.674232495649627, 0.29835434927420834],
       [0.050584299599867544, 0.041570003880418205, 0.6354187481674417,
        0.3986785063857874, 0.5084595944730074, 0.8670474706851001,
        0.36140857590939235, 0.2409213929056816],
       [0.009388211498804422, 0.023620258933618743, 0.9736408164262266,
        0.7399078862777397, 0.7488062528640038, 0.2554277257644364,
        0.30264925049127145, 0.9461388999428614],
       [0.07883988731918024, 0.0017270065429840775, 0.6039845030941133,
        0.3639532626616888, 0.5262313183626182, 0.8652658919103794,
        0.40678108805346525, 0.5755788386022481],
       [0.9540309618644877, 0.5327240403611321, 0.6855901805793,
        0.5640275893197222, 0.13744218351987447, 0.14872455349028435,
        0.5148825626731063, 0.6493621882183533],
       [0.6405119756470511, 0.20246051560863665, 0.37182559625980605,
        0.482139301808187, 0.41567697388824854, 0.2100975454404984,
        0.8397969625400235, 0.34510443543833025],
       [0.9489127164550427, 0.6521237457137699, 0.014751187621828254,
        0.02378528081752518, 0.9743674434170639, 0.7452663445973192,
        0.8286861562596548, 0.6489608824012336],
       [0.21414161657249864, 0.48915308382915756, 0.2006957966886107,
        0.23073574278269415, 0.0980793469559107, 0.32074356202586984,
        0.9063595736583626, 0.3935710413318959],
       [0.2534949697648776, 0.3944440560628507, 0.9776990796380705,
        0.9719417901440758, 0.8284878857707938, 0.6803207176868075,
        0.494606674336053, 0.5837932998206363],
       [0.27142073018702517, 0.48636409182146867, 0.6432176370937984,
        0.147565813233259, 0.0918713785953098, 0.8284223449214373,
        0.26330185108612425, 0.5989176732889872],
       [0.15402149868463488, 0.8416710917084362, 0.9492409382006283,
        0.5515293362864999, 0.1021451693521147, 0.7847008657654228,
        0.34524618789660944, 0.34469353408699466],
       [0.25421020971775665, 0.06981048581042482, 0.9349640631240353,
        0.5724989846173517, 0.666283973555698, 0.5437259799913033,
        0.5043224222341601, 0.5823874271596938],
       [0.21665528682150637, 0.5088912617415079, 0.09338202001557094,
        0.4631176619674955, 0.590218200999245, 0.5983282623441194,
        0.975454432507087, 0.8254580108018265],
       [0.14895656357021236, 0.5939203722764016, 0.06944539721023679,
        0.9008623498806172, 0.35576381563735016, 0.4957423619715833,
        0.7598556017713788, 0.21416337375075578],
       [0.7691753685450565, 0.25197024245583044, 0.5333722764366433,
        0.19004542209953035, 0.2903526177361172, 0.05087834519781875,
        0.04712317109672659, 0.29210675167594224],
       [0.9099705747489388, 0.9424611619851552, 0.4741088115856742,
        0.8656187734037556, 0.48393692918726006, 0.30907496524914324,
        0.9056731833417734, 0.5064627806770224]], dtype=object)

In [36]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.5,0.389563,0.917903,0.217864,0.055401,0.515336,0.589619,0.492043,0.76605,0.004824,...,0.948913,0.214142,0.253495,0.271421,0.154021,0.25421,0.216655,0.148957,0.769175,0.909971
1,0.987934,0.572626,0.945934,0.909983,0.305002,0.271089,0.551097,0.66868,0.509367,0.193976,...,0.652124,0.489153,0.394444,0.486364,0.841671,0.06981,0.508891,0.59392,0.25197,0.942461
2,0.776471,0.259443,0.015947,0.992876,0.755997,0.19282,0.002855,0.232298,0.390674,0.361978,...,0.014751,0.200696,0.977699,0.643218,0.949241,0.934964,0.093382,0.069445,0.533372,0.474109
3,0.009564,0.441299,0.705705,0.885682,0.398721,0.800975,0.668781,0.502944,0.455874,0.425081,...,0.023785,0.230736,0.971942,0.147566,0.551529,0.572499,0.463118,0.900862,0.190045,0.865619
4,0.497942,0.933492,0.683594,0.713147,0.992669,0.084744,0.099482,0.412958,0.297596,0.0823,...,0.974367,0.098079,0.828488,0.091871,0.102145,0.666284,0.590218,0.355764,0.290353,0.483937
5,0.230305,0.566215,0.278658,0.873974,0.905399,0.998761,0.168304,0.90382,0.377481,0.252445,...,0.745266,0.320744,0.680321,0.828422,0.784701,0.543726,0.598328,0.495742,0.050878,0.309075
6,0.423188,0.752269,0.301188,0.507514,0.981552,0.231847,0.865633,0.215507,0.431237,0.593576,...,0.828686,0.90636,0.494607,0.263302,0.345246,0.504322,0.975454,0.759856,0.047123,0.905673
7,0.227213,0.536512,0.439558,0.355722,0.88935,0.814675,0.818911,0.533852,0.024887,0.039537,...,0.648961,0.393571,0.583793,0.598918,0.344694,0.582387,0.825458,0.214163,0.292107,0.506463

In [37]:
newdf.head(10)

,0,1,2,3,4,5,6,7
0,0.5,0.987934,0.776471,0.009564,0.497942,0.230305,0.423188,0.227213
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512
2,0.917903,0.945934,0.015947,0.705705,0.683594,0.278658,0.301188,0.439558
3,0.217864,0.909983,0.992876,0.885682,0.713147,0.873974,0.507514,0.355722
4,0.055401,0.305002,0.755997,0.398721,0.992669,0.905399,0.981552,0.889350
5,0.515336,0.271089,0.192820,0.800975,0.084744,0.998761,0.231847,0.814675
6,0.589619,0.551097,0.002855,0.668781,0.099482,0.168304,0.865633,0.818911
7,0.492043,0.668680,0.232298,0.502944,0.412958,0.903820,0.215507,0.533852
8,0.76605,0.509367,0.390674,0.455874,0.297596,0.377481,0.431237,0.024887
9,0.004824,0.193976,0.361978,0.425081,0.082300,0.252445,0.593576,0.039537

In [38]:
newdf.sort_index(axis=0,ascending=False)

,0,1,2,3,4,5,6,7
99,0.909971,0.942461,0.474109,0.865619,0.483937,0.309075,0.905673,0.506463
98,0.769175,0.251970,0.533372,0.190045,0.290353,0.050878,0.047123,0.292107
97,0.148957,0.593920,0.069445,0.900862,0.355764,0.495742,0.759856,0.214163
96,0.216655,0.508891,0.093382,0.463118,0.590218,0.598328,0.975454,0.825458
95,0.25421,0.069810,0.934964,0.572499,0.666284,0.543726,0.504322,0.582387
...,...,...,...,...,...,...,...,...
4,0.055401,0.305002,0.755997,0.398721,0.992669,0.905399,0.981552,0.889350
3,0.217864,0.909983,0.992876,0.885682,0.713147,0.873974,0.507514,0.355722
2,0.917903,0.945934,0.015947,0.705705,0.683594,0.278658,0.301188,0.439558
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512
0,0.5,0.987934,0.776471,0.009564,0.497942,0.230305,0.423188,0.227213

In [39]:
newdf.sort_index(axis=1,ascending=False)

,7,6,5,4,3,2,1,0
0,0.227213,0.423188,0.230305,0.497942,0.009564,0.776471,0.987934,0.5
1,0.536512,0.752269,0.566215,0.933492,0.441299,0.259443,0.572626,0.389563
2,0.439558,0.301188,0.278658,0.683594,0.705705,0.015947,0.945934,0.917903
3,0.355722,0.507514,0.873974,0.713147,0.885682,0.992876,0.909983,0.217864
4,0.889350,0.981552,0.905399,0.992669,0.398721,0.755997,0.305002,0.055401
...,...,...,...,...,...,...,...,...
95,0.582387,0.504322,0.543726,0.666284,0.572499,0.934964,0.069810,0.25421
96,0.825458,0.975454,0.598328,0.590218,0.463118,0.093382,0.508891,0.216655
97,0.214163,0.759856,0.495742,0.355764,0.900862,0.069445,0.593920,0.148957
98,0.292107,0.047123,0.050878,0.290353,0.190045,0.533372,0.251970,0.769175
99,0.506463,0.905673,0.309075,0.483937,0.865619,0.474109,0.942461,0.909971

In [40]:
newdf[5]

0     0.230305
1     0.566215
2     0.278658
3     0.873974
4     0.905399
        ...
95    0.543726
96    0.598328
97    0.495742
98    0.050878
99    0.309075
Name: 5, Length: 100, dtype: float64

In [41]:
newdf2=newdf

In [42]:
newdf2[0][0]=11111

In [43]:
newdf

,0,1,2,3,4,5,6,7
0,11111,0.987934,0.776471,0.009564,0.497942,0.230305,0.423188,0.227213
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512
2,0.917903,0.945934,0.015947,0.705705,0.683594,0.278658,0.301188,0.439558
3,0.217864,0.909983,0.992876,0.885682,0.713147,0.873974,0.507514,0.355722
4,0.055401,0.305002,0.755997,0.398721,0.992669,0.905399,0.981552,0.889350
...,...,...,...,...,...,...,...,...
95,0.25421,0.069810,0.934964,0.572499,0.666284,0.543726,0.504322,0.582387
96,0.216655,0.508891,0.093382,0.463118,0.590218,0.598328,0.975454,0.825458
97,0.148957,0.593920,0.069445,0.900862,0.355764,0.495742,0.759856,0.214163
98,0.769175,0.251970,0.533372,0.190045,0.290353,0.050878,0.047123,0.292107
99,0.909971,0.942461,0.474109,0.865619,0.483937,0.309075,0.905673,0.506463

In [44]:
newdf2=newdf.copy()

In [45]:
newdf2[0][0]=23456

C:\Users\HP\AppData\Local\Temp\ipykernel_38836\3004339863.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0]=23456
C:\Users\HP\AppData\Local\Temp\ipykernel_38836\3004339863.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf2[0][0]=23456

In [46]:
newdf

,0,1,2,3,4,5,6,7
0,11111,0.987934,0.776471,0.009564,0.497942,0.230305,0.423188,0.227213
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512
2,0.917903,0.945934,0.015947,0.705705,0.683594,0.278658,0.301188,0.439558
3,0.217864,0.909983,0.992876,0.885682,0.713147,0.873974,0.507514,0.355722
4,0.055401,0.305002,0.755997,0.398721,0.992669,0.905399,0.981552,0.889350
...,...,...,...,...,...,...,...,...
95,0.25421,0.069810,0.934964,0.572499,0.666284,0.543726,0.504322,0.582387
96,0.216655,0.508891,0.093382,0.463118,0.590218,0.598328,0.975454,0.825458
97,0.148957,0.593920,0.069445,0.900862,0.355764,0.495742,0.759856,0.214163
98,0.769175,0.251970,0.533372,0.190045,0.290353,0.050878,0.047123,0.292107
99,0.909971,0.942461,0.474109,0.865619,0.483937,0.309075,0.905673,0.506463

In [47]:
newdf2

,0,1,2,3,4,5,6,7
0,23456,0.987934,0.776471,0.009564,0.497942,0.230305,0.423188,0.227213
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512
2,0.917903,0.945934,0.015947,0.705705,0.683594,0.278658,0.301188,0.439558
3,0.217864,0.909983,0.992876,0.885682,0.713147,0.873974,0.507514,0.355722
4,0.055401,0.305002,0.755997,0.398721,0.992669,0.905399,0.981552,0.889350
...,...,...,...,...,...,...,...,...
95,0.25421,0.069810,0.934964,0.572499,0.666284,0.543726,0.504322,0.582387
96,0.216655,0.508891,0.093382,0.463118,0.590218,0.598328,0.975454,0.825458
97,0.148957,0.593920,0.069445,0.900862,0.355764,0.495742,0.759856,0.214163
98,0.769175,0.251970,0.533372,0.190045,0.290353,0.050878,0.047123,0.292107
99,0.909971,0.942461,0.474109,0.865619,0.483937,0.309075,0.905673,0.506463

In [48]:
newdf.loc(0,0)=12321233

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (3046687601.py, line 1)

In [49]:
newdf

,0,1,2,3,4,5,6,7
0,11111,0.987934,0.776471,0.009564,0.497942,0.230305,0.423188,0.227213
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512
2,0.917903,0.945934,0.015947,0.705705,0.683594,0.278658,0.301188,0.439558
3,0.217864,0.909983,0.992876,0.885682,0.713147,0.873974,0.507514,0.355722
4,0.055401,0.305002,0.755997,0.398721,0.992669,0.905399,0.981552,0.889350
...,...,...,...,...,...,...,...,...
95,0.25421,0.069810,0.934964,0.572499,0.666284,0.543726,0.504322,0.582387
96,0.216655,0.508891,0.093382,0.463118,0.590218,0.598328,0.975454,0.825458
97,0.148957,0.593920,0.069445,0.900862,0.355764,0.495742,0.759856,0.214163
98,0.769175,0.251970,0.533372,0.190045,0.290353,0.050878,0.047123,0.292107
99,0.909971,0.942461,0.474109,0.865619,0.483937,0.309075,0.905673,0.506463

In [50]:
newdf.loc[0,0]=123456789

In [51]:
newdf

,0,1,2,3,4,5,6,7
0,123456789,0.987934,0.776471,0.009564,0.497942,0.230305,0.423188,0.227213
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512
2,0.917903,0.945934,0.015947,0.705705,0.683594,0.278658,0.301188,0.439558
3,0.217864,0.909983,0.992876,0.885682,0.713147,0.873974,0.507514,0.355722
4,0.055401,0.305002,0.755997,0.398721,0.992669,0.905399,0.981552,0.889350
...,...,...,...,...,...,...,...,...
95,0.25421,0.069810,0.934964,0.572499,0.666284,0.543726,0.504322,0.582387
96,0.216655,0.508891,0.093382,0.463118,0.590218,0.598328,0.975454,0.825458
97,0.148957,0.593920,0.069445,0.900862,0.355764,0.495742,0.759856,0.214163
98,0.769175,0.251970,0.533372,0.190045,0.290353,0.050878,0.047123,0.292107
99,0.909971,0.942461,0.474109,0.865619,0.483937,0.309075,0.905673,0.506463

In [52]:
newdf.head(2)

,0,1,2,3,4,5,6,7
0,123456789,0.987934,0.776471,0.009564,0.497942,0.230305,0.423188,0.227213
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512

In [53]:
newdf.columns=list("ABCDEFGH")

In [54]:
newdf

,A,B,C,D,E,F,G,H
0,123456789,0.987934,0.776471,0.009564,0.497942,0.230305,0.423188,0.227213
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512
2,0.917903,0.945934,0.015947,0.705705,0.683594,0.278658,0.301188,0.439558
3,0.217864,0.909983,0.992876,0.885682,0.713147,0.873974,0.507514,0.355722
4,0.055401,0.305002,0.755997,0.398721,0.992669,0.905399,0.981552,0.889350
...,...,...,...,...,...,...,...,...
95,0.25421,0.069810,0.934964,0.572499,0.666284,0.543726,0.504322,0.582387
96,0.216655,0.508891,0.093382,0.463118,0.590218,0.598328,0.975454,0.825458
97,0.148957,0.593920,0.069445,0.900862,0.355764,0.495742,0.759856,0.214163
98,0.769175,0.251970,0.533372,0.190045,0.290353,0.050878,0.047123,0.292107
99,0.909971,0.942461,0.474109,0.865619,0.483937,0.309075,0.905673,0.506463

In [55]:
newdf.drop(0)

,A,B,C,D,E,F,G,H
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512
2,0.917903,0.945934,0.015947,0.705705,0.683594,0.278658,0.301188,0.439558
3,0.217864,0.909983,0.992876,0.885682,0.713147,0.873974,0.507514,0.355722
4,0.055401,0.305002,0.755997,0.398721,0.992669,0.905399,0.981552,0.889350
5,0.515336,0.271089,0.192820,0.800975,0.084744,0.998761,0.231847,0.814675
...,...,...,...,...,...,...,...,...
95,0.25421,0.069810,0.934964,0.572499,0.666284,0.543726,0.504322,0.582387
96,0.216655,0.508891,0.093382,0.463118,0.590218,0.598328,0.975454,0.825458
97,0.148957,0.593920,0.069445,0.900862,0.355764,0.495742,0.759856,0.214163
98,0.769175,0.251970,0.533372,0.190045,0.290353,0.050878,0.047123,0.292107
99,0.909971,0.942461,0.474109,0.865619,0.483937,0.309075,0.905673,0.506463

In [57]:
newdf.drop(0)

,A,B,C,D,E,F,G,H
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512
2,0.917903,0.945934,0.015947,0.705705,0.683594,0.278658,0.301188,0.439558
3,0.217864,0.909983,0.992876,0.885682,0.713147,0.873974,0.507514,0.355722
4,0.055401,0.305002,0.755997,0.398721,0.992669,0.905399,0.981552,0.889350
5,0.515336,0.271089,0.192820,0.800975,0.084744,0.998761,0.231847,0.814675
...,...,...,...,...,...,...,...,...
95,0.25421,0.069810,0.934964,0.572499,0.666284,0.543726,0.504322,0.582387
96,0.216655,0.508891,0.093382,0.463118,0.590218,0.598328,0.975454,0.825458
97,0.148957,0.593920,0.069445,0.900862,0.355764,0.495742,0.759856,0.214163
98,0.769175,0.251970,0.533372,0.190045,0.290353,0.050878,0.047123,0.292107
99,0.909971,0.942461,0.474109,0.865619,0.483937,0.309075,0.905673,0.506463

In [60]:
newdf3=newdf.drop('A',axis=1)

In [63]:
newdf3.describe()

,B,C,D,E,F,G,H
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,0.506190,0.470866,0.460008,0.467666,0.522114,0.541470,0.516513
std,0.298563,0.309248,0.261872,0.300571,0.266640,0.276092,0.287141
min,0.000735,0.001237,0.009564,0.000854,0.023980,0.025608,0.024887
25%,0.250828,0.193156,0.232290,0.186972,0.301471,0.308479,0.308359
50%,0.512379,0.484224,0.459496,0.466348,0.545785,0.516111,0.480708
75%,0.768275,0.690229,0.636983,0.750407,0.743850,0.788307,0.798846
max,0.993706,0.999588,0.999069,0.992669,0.998761,0.996515,0.994155

In [65]:
newdf.loc[[0,1],['D','E']]

          D         E
0  0.009564  0.497942
1  0.441299  0.933492

In [66]:
newdf.loc[:,['D','E']]

           D         E
0   0.009564  0.497942
1   0.441299  0.933492
2   0.705705  0.683594
3   0.885682  0.713147
4   0.398721  0.992669
..       ...       ...
95  0.572499  0.666284
96  0.463118  0.590218
97  0.900862  0.355764
98  0.190045  0.290353
99  0.865619  0.483937

[100 rows x 2 columns]

In [67]:
newdf.loc[[0,1],:]

,A,B,C,D,E,F,G,H
0,123456789,0.987934,0.776471,0.009564,0.497942,0.230305,0.423188,0.227213
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512

In [68]:
newdf.loc[newdf['A']<0.5]

,A,B,C,D,E,F,G,H
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512
3,0.217864,0.909983,0.992876,0.885682,0.713147,0.873974,0.507514,0.355722
4,0.055401,0.305002,0.755997,0.398721,0.992669,0.905399,0.981552,0.889350
7,0.492043,0.668680,0.232298,0.502944,0.412958,0.903820,0.215507,0.533852
9,0.004824,0.193976,0.361978,0.425081,0.082300,0.252445,0.593576,0.039537
10,0.00222,0.376930,0.729926,0.755399,0.919932,0.777058,0.285469,0.152125
13,0.274466,0.964937,0.625500,0.537463,0.750221,0.467197,0.460998,0.475847
14,0.428187,0.856482,0.992961,0.398497,0.821687,0.507067,0.956113,0.847531
18,0.131547,0.200343,0.693182,0.448990,0.474858,0.483885,0.295746,0.894585
19,0.164402,0.788352,0.262281,0.865426,0.280347,0.522370,0.310422,0.754816
23,0.090957,0.496409,0.395491,0.400947,0.913959,0.362348,0.899039,0.484141
25,0.174061,0.132725,0.647591,0.904672,0.195320,0.617925,0.334392,0.941282
26,0.049149,0.942304,0.394252,0.304507,0.506774,0.210110,0.260593,0.696562
32,0.134269,0.415889,0.303984,0.183175,0.531943,0.713118,0.891828,0.072487
33,0.162946,0.961948,0.689244,0.814122,0.899689,0.760866,0.138791,0.048982
37,0.292542,0.993706,0.022450,0.342192,0.148818,0.810246,0.828085,0.908940
38,0.188273,0.436061,0.101943,0.750184,0.316232,0.638031,0.025608,0.426955
39,0.098432,0.053668,0.798928,0.556698,0.843351,0.601972,0.475379,0.986274
40,0.066735,0.973826,0.122212,0.523353,0.805034,0.204979,0.746363,0.412544
41,0.491371,0.049619,0.388184,0.292420,0.061766,0.536546,0.929746,0.476132
42,0.458101,0.168883,0.058593,0.576977,0.898685,0.144637,0.036982,0.861546
44,0.111344,0.557991,0.992890,0.745697,0.607309,0.172968,0.617648,0.994155
47,0.370147,0.649059,0.487225,0.129985,0.236339,0.971586,0.725923,0.475955
49,0.14637,0.329380,0.981025,0.245101,0.007165,0.315922,0.718715,0.080117
52,0.328348,0.291226,0.099417,0.112262,0.931260,0.386752,0.392084,0.341932
55,0.339859,0.695037,0.851770,0.221636,0.288841,0.974151,0.581898,0.480953
56,0.04299,0.389554,0.004823,0.435321,0.661548,0.829362,0.996515,0.133036
57,0.213671,0.831369,0.656122,0.121605,0.000854,0.275600,0.133236,0.711987
58,0.224716,0.166992,0.122175,0.642691,0.509764,0.064886,0.625933,0.289105
59,0.200088,0.857927,0.213312,0.999069,0.819629,0.165816,0.687470,0.040174
62,0.438125,0.168146,0.253880,0.763748,0.484238,0.523934,0.112318,0.313657
64,0.152039,0.644872,0.481224,0.284541,0.554346,0.643273,0.269716,0.474956
66,0.426464,0.264146,0.291004,0.081443,0.283180,0.376598,0.761784,0.182229
68,0.357113,0.900519,0.024895,0.923386,0.377504,0.832706,0.377243,0.114583
69,0.098804,0.738734,0.502203,0.405860,0.144865,0.831872,0.517339,0.200598
70,0.332436,0.570103,0.813533,0.194717,0.536107,0.623363,0.811051,0.811984
71,0.260096,0.982176,0.887172,0.591071,0.222839,0.382258,0.750987,0.384758
73,0.10976,0.689655,0.516726,0.306507,0.690100,0.878509,0.430033,0.311694
74,0.221665,0.869582,0.020359,0.297369,0.765503,0.806404,0.938836,0.244019
75,0.373087,0.605471,0.158848,0.508742,0.103889,0.069315,0.952604,0.064542
76,0.091656,0.318344,0.141268,0.232808,0.780316,0.719854,0.109272,0.406078
78,0.051319,0.720327,0.978863,0.385883,0.115675,0.728584,0.707398,0.920208
79,0.259369,0.029037,0.305130,0.630651,0.610011,0.573400,0.756857,0.991561
82,0.325937,0.267883,0.818134,0.764419,0.216746,0.251569,0.380663,0.858669
83,0.145574,0.000735,0.109223,0.114576,0.696114,0.761781,0.076699,0.801702
85,0.050584,0.041570,0.635419,0.398679,0.508460,0.867047,0.361409,0.240921
86,0.009388,0.023620,0.973641,0.739908,0.748806,0.255428,0.302649,0.946139
87,0.07884,0.001727,0.603985,0.363953,0.526231,0.865266,0.406781,0.575579
91,0.214142,0.489153,0.200696,0.230736,0.098079,0.320744,0.906360,0.393571
92,0.253495,0.394444,0.977699,0.971942,0.828488,0.680321,0.494607,0.583793
93,0.271421,0.486364,0.643218,0.147566,0.091871,0.828422,0.263302,0.598918
94,0.154021,0.841671,0.949241,0.551529,0.102145,0.784701,0.345246,0.344694
95,0.25421,0.069810,0.934964,0.572499,0.666284,0.543726,0.504322,0.582387
96,0.216655,0.508891,0.093382,0.463118,0.590218,0.598328,0.975454,0.825458
97,0.148957,0.593920,0.069445,0.900862,0.355764,0.495742,0.759856,0.214163

In [71]:
newdf.loc[newdf['A']<0.5]

,A,B,C,D,E,F,G,H
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512
3,0.217864,0.909983,0.992876,0.885682,0.713147,0.873974,0.507514,0.355722
4,0.055401,0.305002,0.755997,0.398721,0.992669,0.905399,0.981552,0.889350
7,0.492043,0.668680,0.232298,0.502944,0.412958,0.903820,0.215507,0.533852
9,0.004824,0.193976,0.361978,0.425081,0.082300,0.252445,0.593576,0.039537
10,0.00222,0.376930,0.729926,0.755399,0.919932,0.777058,0.285469,0.152125
13,0.274466,0.964937,0.625500,0.537463,0.750221,0.467197,0.460998,0.475847
14,0.428187,0.856482,0.992961,0.398497,0.821687,0.507067,0.956113,0.847531
18,0.131547,0.200343,0.693182,0.448990,0.474858,0.483885,0.295746,0.894585
19,0.164402,0.788352,0.262281,0.865426,0.280347,0.522370,0.310422,0.754816
23,0.090957,0.496409,0.395491,0.400947,0.913959,0.362348,0.899039,0.484141
25,0.174061,0.132725,0.647591,0.904672,0.195320,0.617925,0.334392,0.941282
26,0.049149,0.942304,0.394252,0.304507,0.506774,0.210110,0.260593,0.696562
32,0.134269,0.415889,0.303984,0.183175,0.531943,0.713118,0.891828,0.072487
33,0.162946,0.961948,0.689244,0.814122,0.899689,0.760866,0.138791,0.048982
37,0.292542,0.993706,0.022450,0.342192,0.148818,0.810246,0.828085,0.908940
38,0.188273,0.436061,0.101943,0.750184,0.316232,0.638031,0.025608,0.426955
39,0.098432,0.053668,0.798928,0.556698,0.843351,0.601972,0.475379,0.986274
40,0.066735,0.973826,0.122212,0.523353,0.805034,0.204979,0.746363,0.412544
41,0.491371,0.049619,0.388184,0.292420,0.061766,0.536546,0.929746,0.476132
42,0.458101,0.168883,0.058593,0.576977,0.898685,0.144637,0.036982,0.861546
44,0.111344,0.557991,0.992890,0.745697,0.607309,0.172968,0.617648,0.994155
47,0.370147,0.649059,0.487225,0.129985,0.236339,0.971586,0.725923,0.475955
49,0.14637,0.329380,0.981025,0.245101,0.007165,0.315922,0.718715,0.080117
52,0.328348,0.291226,0.099417,0.112262,0.931260,0.386752,0.392084,0.341932
55,0.339859,0.695037,0.851770,0.221636,0.288841,0.974151,0.581898,0.480953
56,0.04299,0.389554,0.004823,0.435321,0.661548,0.829362,0.996515,0.133036
57,0.213671,0.831369,0.656122,0.121605,0.000854,0.275600,0.133236,0.711987
58,0.224716,0.166992,0.122175,0.642691,0.509764,0.064886,0.625933,0.289105
59,0.200088,0.857927,0.213312,0.999069,0.819629,0.165816,0.687470,0.040174
62,0.438125,0.168146,0.253880,0.763748,0.484238,0.523934,0.112318,0.313657
64,0.152039,0.644872,0.481224,0.284541,0.554346,0.643273,0.269716,0.474956
66,0.426464,0.264146,0.291004,0.081443,0.283180,0.376598,0.761784,0.182229
68,0.357113,0.900519,0.024895,0.923386,0.377504,0.832706,0.377243,0.114583
69,0.098804,0.738734,0.502203,0.405860,0.144865,0.831872,0.517339,0.200598
70,0.332436,0.570103,0.813533,0.194717,0.536107,0.623363,0.811051,0.811984
71,0.260096,0.982176,0.887172,0.591071,0.222839,0.382258,0.750987,0.384758
73,0.10976,0.689655,0.516726,0.306507,0.690100,0.878509,0.430033,0.311694
74,0.221665,0.869582,0.020359,0.297369,0.765503,0.806404,0.938836,0.244019
75,0.373087,0.605471,0.158848,0.508742,0.103889,0.069315,0.952604,0.064542
76,0.091656,0.318344,0.141268,0.232808,0.780316,0.719854,0.109272,0.406078
78,0.051319,0.720327,0.978863,0.385883,0.115675,0.728584,0.707398,0.920208
79,0.259369,0.029037,0.305130,0.630651,0.610011,0.573400,0.756857,0.991561
82,0.325937,0.267883,0.818134,0.764419,0.216746,0.251569,0.380663,0.858669
83,0.145574,0.000735,0.109223,0.114576,0.696114,0.761781,0.076699,0.801702
85,0.050584,0.041570,0.635419,0.398679,0.508460,0.867047,0.361409,0.240921
86,0.009388,0.023620,0.973641,0.739908,0.748806,0.255428,0.302649,0.946139
87,0.07884,0.001727,0.603985,0.363953,0.526231,0.865266,0.406781,0.575579
91,0.214142,0.489153,0.200696,0.230736,0.098079,0.320744,0.906360,0.393571
92,0.253495,0.394444,0.977699,0.971942,0.828488,0.680321,0.494607,0.583793
93,0.271421,0.486364,0.643218,0.147566,0.091871,0.828422,0.263302,0.598918
94,0.154021,0.841671,0.949241,0.551529,0.102145,0.784701,0.345246,0.344694
95,0.25421,0.069810,0.934964,0.572499,0.666284,0.543726,0.504322,0.582387
96,0.216655,0.508891,0.093382,0.463118,0.590218,0.598328,0.975454,0.825458
97,0.148957,0.593920,0.069445,0.900862,0.355764,0.495742,0.759856,0.214163

In [76]:
newdf.loc[(newdf['A']<0.5) & (newdf['C']>0.7)]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3767698617.py, line 1)

In [75]:
newdf.iloc[1,5]

0.5662154725350815

In [77]:
newdf

,A,B,C,D,E,F,G,H
0,123456789,0.987934,0.776471,0.009564,0.497942,0.230305,0.423188,0.227213
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512
2,0.917903,0.945934,0.015947,0.705705,0.683594,0.278658,0.301188,0.439558
3,0.217864,0.909983,0.992876,0.885682,0.713147,0.873974,0.507514,0.355722
4,0.055401,0.305002,0.755997,0.398721,0.992669,0.905399,0.981552,0.889350
...,...,...,...,...,...,...,...,...
95,0.25421,0.069810,0.934964,0.572499,0.666284,0.543726,0.504322,0.582387
96,0.216655,0.508891,0.093382,0.463118,0.590218,0.598328,0.975454,0.825458
97,0.148957,0.593920,0.069445,0.900862,0.355764,0.495742,0.759856,0.214163
98,0.769175,0.251970,0.533372,0.190045,0.290353,0.050878,0.047123,0.292107
99,0.909971,0.942461,0.474109,0.865619,0.483937,0.309075,0.905673,0.506463

In [78]:
newdf.drop([0])

,A,B,C,D,E,F,G,H
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512
2,0.917903,0.945934,0.015947,0.705705,0.683594,0.278658,0.301188,0.439558
3,0.217864,0.909983,0.992876,0.885682,0.713147,0.873974,0.507514,0.355722
4,0.055401,0.305002,0.755997,0.398721,0.992669,0.905399,0.981552,0.889350
5,0.515336,0.271089,0.192820,0.800975,0.084744,0.998761,0.231847,0.814675
...,...,...,...,...,...,...,...,...
95,0.25421,0.069810,0.934964,0.572499,0.666284,0.543726,0.504322,0.582387
96,0.216655,0.508891,0.093382,0.463118,0.590218,0.598328,0.975454,0.825458
97,0.148957,0.593920,0.069445,0.900862,0.355764,0.495742,0.759856,0.214163
98,0.769175,0.251970,0.533372,0.190045,0.290353,0.050878,0.047123,0.292107
99,0.909971,0.942461,0.474109,0.865619,0.483937,0.309075,0.905673,0.506463

In [79]:
newdf

,A,B,C,D,E,F,G,H
0,123456789,0.987934,0.776471,0.009564,0.497942,0.230305,0.423188,0.227213
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512
2,0.917903,0.945934,0.015947,0.705705,0.683594,0.278658,0.301188,0.439558
3,0.217864,0.909983,0.992876,0.885682,0.713147,0.873974,0.507514,0.355722
4,0.055401,0.305002,0.755997,0.398721,0.992669,0.905399,0.981552,0.889350
...,...,...,...,...,...,...,...,...
95,0.25421,0.069810,0.934964,0.572499,0.666284,0.543726,0.504322,0.582387
96,0.216655,0.508891,0.093382,0.463118,0.590218,0.598328,0.975454,0.825458
97,0.148957,0.593920,0.069445,0.900862,0.355764,0.495742,0.759856,0.214163
98,0.769175,0.251970,0.533372,0.190045,0.290353,0.050878,0.047123,0.292107
99,0.909971,0.942461,0.474109,0.865619,0.483937,0.309075,0.905673,0.506463

In [80]:
newdf.drop([0],inplace=True)

In [81]:
newdf

,A,B,C,D,E,F,G,H
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512
2,0.917903,0.945934,0.015947,0.705705,0.683594,0.278658,0.301188,0.439558
3,0.217864,0.909983,0.992876,0.885682,0.713147,0.873974,0.507514,0.355722
4,0.055401,0.305002,0.755997,0.398721,0.992669,0.905399,0.981552,0.889350
5,0.515336,0.271089,0.192820,0.800975,0.084744,0.998761,0.231847,0.814675
...,...,...,...,...,...,...,...,...
95,0.25421,0.069810,0.934964,0.572499,0.666284,0.543726,0.504322,0.582387
96,0.216655,0.508891,0.093382,0.463118,0.590218,0.598328,0.975454,0.825458
97,0.148957,0.593920,0.069445,0.900862,0.355764,0.495742,0.759856,0.214163
98,0.769175,0.251970,0.533372,0.190045,0.290353,0.050878,0.047123,0.292107
99,0.909971,0.942461,0.474109,0.865619,0.483937,0.309075,0.905673,0.506463

In [84]:
newdf.drop([2],inplace=True)

In [85]:
newdf.head(3)

,A,B,C,D,E,F,G,H
1,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512
3,0.217864,0.909983,0.992876,0.885682,0.713147,0.873974,0.507514,0.355722
4,0.055401,0.305002,0.755997,0.398721,0.992669,0.905399,0.981552,0.889350

In [88]:
newdf.reset_index(drop=True,inplace=True)

In [89]:
newdf.head(10)

,A,B,C,D,E,F,G,H
0,0.389563,0.572626,0.259443,0.441299,0.933492,0.566215,0.752269,0.536512
1,0.217864,0.909983,0.992876,0.885682,0.713147,0.873974,0.507514,0.355722
2,0.055401,0.305002,0.755997,0.398721,0.992669,0.905399,0.981552,0.889350
3,0.515336,0.271089,0.192820,0.800975,0.084744,0.998761,0.231847,0.814675
4,0.589619,0.551097,0.002855,0.668781,0.099482,0.168304,0.865633,0.818911
5,0.492043,0.668680,0.232298,0.502944,0.412958,0.903820,0.215507,0.533852
6,0.76605,0.509367,0.390674,0.455874,0.297596,0.377481,0.431237,0.024887
7,0.004824,0.193976,0.361978,0.425081,0.082300,0.252445,0.593576,0.039537
8,0.00222,0.376930,0.729926,0.755399,0.919932,0.777058,0.285469,0.152125
9,0.573067,0.560065,0.524685,0.131970,0.554474,0.681577,0.649158,0.220050

In [90]:
newdf['B']=None

In [91]:
newdf

           A     B         C         D         E         F         G         H
0   0.389563  None  0.259443  0.441299  0.933492  0.566215  0.752269  0.536512
1   0.217864  None  0.992876  0.885682  0.713147  0.873974  0.507514  0.355722
2   0.055401  None  0.755997  0.398721  0.992669  0.905399  0.981552  0.889350
3   0.515336  None  0.192820  0.800975  0.084744  0.998761  0.231847  0.814675
4   0.589619  None  0.002855  0.668781  0.099482  0.168304  0.865633  0.818911
..       ...   ...       ...       ...       ...       ...       ...       ...
93   0.25421  None  0.934964  0.572499  0.666284  0.543726  0.504322  0.582387
94  0.216655  None  0.093382  0.463118  0.590218  0.598328  0.975454  0.825458
95  0.148957  None  0.069445  0.900862  0.355764  0.495742  0.759856  0.214163
96  0.769175  None  0.533372  0.190045  0.290353  0.050878  0.047123  0.292107
97  0.909971  None  0.474109  0.865619  0.483937  0.309075  0.905673  0.506463

[98 rows x 8 columns]

In [93]:
newdf['B'].isnull()

0     True
1     True
2     True
3     True
4     True
      ...
93    True
94    True
95    True
96    True
97    True
Name: B, Length: 98, dtype: bool

In [94]:
newdf.shape

(98, 8)

In [95]:
newdf.info

<bound method DataFrame.info of            A     B         C         D         E         F         G         H
0   0.389563  None  0.259443  0.441299  0.933492  0.566215  0.752269  0.536512
1   0.217864  None  0.992876  0.885682  0.713147  0.873974  0.507514  0.355722
2   0.055401  None  0.755997  0.398721  0.992669  0.905399  0.981552  0.889350
3   0.515336  None  0.192820  0.800975  0.084744  0.998761  0.231847  0.814675
4   0.589619  None  0.002855  0.668781  0.099482  0.168304  0.865633  0.818911
..       ...   ...       ...       ...       ...       ...       ...       ...
93   0.25421  None  0.934964  0.572499  0.666284  0.543726  0.504322  0.582387
94  0.216655  None  0.093382  0.463118  0.590218  0.598328  0.975454  0.825458
95  0.148957  None  0.069445  0.900862  0.355764  0.495742  0.759856  0.214163
96  0.769175  None  0.533372  0.190045  0.290353  0.050878  0.047123  0.292107
97  0.909971  None  0.474109  0.865619  0.483937  0.309075  0.905673  0.506463

[98 rows x 8 columns]>